'use client';

/**
 * IndexedDB utility for offline session storage
 * Stores typing sessions locally when offline, syncs when online
 */

export interface OfflineTypingSession {
  id?: number; // Auto-generated by IndexedDB
  localId: string; // UUID for tracking before sync
  userId?: number; // May not be available if offline
  challengeId: number;
  wpm: number;
  rawWpm: number;
  accuracy: number;
  keystrokes: number;
  errors: number;
  durationMs: number;
  completedAt: number; // timestamp
  synced: boolean;
  keystrokeLogs: OfflineKeystrokeLog[];
}

export interface OfflineKeystrokeLog {
  timestamp: number;
  expected: string;
  actual: string;
  isCorrect: boolean;
  latencyMs: number;
}

const DB_NAME = 'sokudo-offline';
const DB_VERSION = 1;
const SESSIONS_STORE = 'typing_sessions';

let dbInstance: IDBDatabase | null = null;

/**
 * Initialize IndexedDB connection
 */
export async function initDB(): Promise<IDBDatabase> {
  if (dbInstance) {
    return dbInstance;
  }

  return new Promise((resolve, reject) => {
    if (typeof window === 'undefined' || !('indexedDB' in window)) {
      reject(new Error('IndexedDB is not supported in this environment'));
      return;
    }

    const request = indexedDB.open(DB_NAME, DB_VERSION);

    request.onerror = () => {
      reject(new Error('Failed to open IndexedDB'));
    };

    request.onsuccess = () => {
      dbInstance = request.result;
      resolve(dbInstance);
    };

    request.onupgradeneeded = (event) => {
      const db = (event.target as IDBOpenDBRequest).result;

      // Create typing_sessions object store
      if (!db.objectStoreNames.contains(SESSIONS_STORE)) {
        const store = db.createObjectStore(SESSIONS_STORE, {
          keyPath: 'id',
          autoIncrement: true,
        });

        // Create indexes for efficient querying
        store.createIndex('localId', 'localId', { unique: true });
        store.createIndex('synced', 'synced', { unique: false });
        store.createIndex('completedAt', 'completedAt', { unique: false });
        store.createIndex('challengeId', 'challengeId', { unique: false });
      }
    };
  });
}

/**
 * Save a typing session to IndexedDB
 */
export async function saveSessionOffline(
  session: Omit<OfflineTypingSession, 'id' | 'synced'>
): Promise<string> {
  const db = await initDB();

  return new Promise((resolve, reject) => {
    const transaction = db.transaction([SESSIONS_STORE], 'readwrite');
    const store = transaction.objectStore(SESSIONS_STORE);

    const sessionWithSync: Omit<OfflineTypingSession, 'id'> = {
      ...session,
      synced: false,
    };

    const request = store.add(sessionWithSync);

    request.onsuccess = () => {
      resolve(session.localId);
    };

    request.onerror = () => {
      reject(new Error('Failed to save session offline'));
    };
  });
}

/**
 * Get all unsynced sessions
 */
export async function getUnsyncedSessions(): Promise<OfflineTypingSession[]> {
  const db = await initDB();

  return new Promise((resolve, reject) => {
    const transaction = db.transaction([SESSIONS_STORE], 'readonly');
    const store = transaction.objectStore(SESSIONS_STORE);

    // Get all sessions and filter for unsynced
    const request = store.getAll();

    request.onsuccess = () => {
      const allSessions = request.result as OfflineTypingSession[];
      const unsyncedSessions = allSessions.filter(session => !session.synced);
      resolve(unsyncedSessions);
    };

    request.onerror = () => {
      reject(new Error('Failed to get unsynced sessions'));
    };
  });
}

/**
 * Mark a session as synced
 */
export async function markSessionAsSynced(localId: string): Promise<void> {
  const db = await initDB();

  return new Promise((resolve, reject) => {
    const transaction = db.transaction([SESSIONS_STORE], 'readwrite');
    const store = transaction.objectStore(SESSIONS_STORE);
    const index = store.index('localId');

    const getRequest = index.get(localId);

    getRequest.onsuccess = () => {
      const session = getRequest.result;
      if (!session) {
        reject(new Error(`Session with localId ${localId} not found`));
        return;
      }

      session.synced = true;
      const updateRequest = store.put(session);

      updateRequest.onsuccess = () => {
        resolve();
      };

      updateRequest.onerror = () => {
        reject(new Error('Failed to mark session as synced'));
      };
    };

    getRequest.onerror = () => {
      reject(new Error('Failed to find session'));
    };
  });
}

/**
 * Delete a synced session
 */
export async function deleteSession(localId: string): Promise<void> {
  const db = await initDB();

  return new Promise((resolve, reject) => {
    const transaction = db.transaction([SESSIONS_STORE], 'readwrite');
    const store = transaction.objectStore(SESSIONS_STORE);
    const index = store.index('localId');

    const getRequest = index.get(localId);

    getRequest.onsuccess = () => {
      const session = getRequest.result;
      if (!session) {
        resolve(); // Already deleted
        return;
      }

      const deleteRequest = store.delete(session.id!);

      deleteRequest.onsuccess = () => {
        resolve();
      };

      deleteRequest.onerror = () => {
        reject(new Error('Failed to delete session'));
      };
    };

    getRequest.onerror = () => {
      reject(new Error('Failed to find session to delete'));
    };
  });
}

/**
 * Get all sessions (for debugging/export)
 */
export async function getAllSessions(): Promise<OfflineTypingSession[]> {
  const db = await initDB();

  return new Promise((resolve, reject) => {
    const transaction = db.transaction([SESSIONS_STORE], 'readonly');
    const store = transaction.objectStore(SESSIONS_STORE);

    const request = store.getAll();

    request.onsuccess = () => {
      resolve(request.result);
    };

    request.onerror = () => {
      reject(new Error('Failed to get all sessions'));
    };
  });
}

/**
 * Get session count
 */
export async function getSessionCount(): Promise<number> {
  const db = await initDB();

  return new Promise((resolve, reject) => {
    const transaction = db.transaction([SESSIONS_STORE], 'readonly');
    const store = transaction.objectStore(SESSIONS_STORE);

    const request = store.count();

    request.onsuccess = () => {
      resolve(request.result);
    };

    request.onerror = () => {
      reject(new Error('Failed to get session count'));
    };
  });
}

/**
 * Clear all sessions (for testing)
 */
export async function clearAllSessions(): Promise<void> {
  const db = await initDB();

  return new Promise((resolve, reject) => {
    const transaction = db.transaction([SESSIONS_STORE], 'readwrite');
    const store = transaction.objectStore(SESSIONS_STORE);

    const request = store.clear();

    request.onsuccess = () => {
      resolve();
    };

    request.onerror = () => {
      reject(new Error('Failed to clear sessions'));
    };
  });
}

/**
 * Close IndexedDB connection
 */
export function closeDB(): void {
  if (dbInstance) {
    dbInstance.close();
    dbInstance = null;
  }
}

/**
 * Generate a unique local ID for a session
 */
export function generateLocalId(): string {
  return `${Date.now()}-${Math.random().toString(36).substring(2, 15)}`;
}
